crossbrowser initial implementation
hmcts/em-media-viewer pull request #403
Opened 2021-10-13 13:56 UTC by Ferdi-Cocelli

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EM-3993

### Description ###
Cross browser automation for media viewer e2e tests and make sure the e2e tests should run in HMCTS users supported browsers.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[X] No
```

2021-11-08 10:04 UTC, matt-k1998 submitted a review, later dismissed

2021-11-11 14:14 UTC, phani-perla1 requested changes

2022-01-10 10:08 UTC, matt-k1998 commented on Jenkinsfile_nightly
> +  env.TEST_URL = 'http://em-showcase-aat.service.core-compute-aat.internal/media-viewer'
yes, this is the correct URL for media viewer on AAT

2022-01-10 10:26 UTC, matt-k1998 commented on e2e/saucelabs.conf.js
> +//    {
I have decided to run the tests across two browsers for now (chrome on MacOS and firefox on Windows 10). Once this PR is merged, we can monitor those and add more browser combinations in the future.

2022-01-10 14:22 UTC, matt-k1998 approved these changes

2022-01-13 10:59 UTC, yogesh-hullatti approved these changes

2022-01-13 11:07 UTC, merged