Em 4800 outline page numbers
hmcts/em-media-viewer pull request #627
Opened 2022-12-15 10:12 UTC by MichaelJacob21012

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EM-4800
https://tools.hmcts.net/jira/browse/EM-4798
https://tools.hmcts.net/jira/browse/EM-4865
https://tools.hmcts.net/jira/browse/EM-4866

### Change description ###
Add page numbers to outline and highlight current section

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-01-06 09:04 UTC, MunishSharmaHMCTS approved these changes

2023-01-09 16:14 UTC, phani-perla1 requested changes

2023-01-09 16:14 UTC, phani-perla1 commented on test/end-to-end/mvFeatures/indexAndOutline.js
> +}).tag('@EM-4865')
update tag name as @ci

2023-01-09 17:21 UTC, phani-perla1 approved these changes

2023-01-13 12:53 UTC, merged