Em 2669 redact page
hmcts/em-media-viewer pull request #657
Opened 2023-01-16 08:53 UTC by MichaelJacob21012

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/EM-2669

### Change description ###
Enable redact page

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-01-16 10:36 UTC, phani-perla1 requested changes

2023-01-16 10:36 UTC, phani-perla1 commented on test/end-to-end/helpers/mvCaseHelper.js
> +  await executeTestsOnPreview(I, caseId, mediaType);
We have an existing test script that redacting content on "First Page"  using below functions:
1) Draw Box function
2) Redact Text Function

So exclude this text  from master pipeline  execution and tag to "nightly build(np)"

![image](https://user-images.githubusercontent.com/87771652/212658265-8eff7643-dfd1-4c88-8628-e9aa60ce70dd.png)

2023-01-16 10:58 UTC, phani-perla1 approved these changes
LGTM

2023-01-16 10:58 UTC, phani-perla1 commented on test/end-to-end/mvFeatures/redact.js
> +}).tag('@ci')
update tag name as "@np" (nightly pipeline)

2023-01-16 10:58 UTC, phani-perla1 commented on test/end-to-end/mvFeatures/redact.js
> +}).tag('@ci')
update tag name as "@np" (nightly pipeline)  .

This test won't run until the code is deployed on AAT  & 
moreover AAT MV execution using  different test data so you need to update the code according AAT & Preview test data.

For further details look at AAT Test Data case:
![image](https://user-images.githubusercontent.com/87771652/212659182-a3a7ceeb-40eb-483d-91dc-00bb673e0cd9.png)

2023-01-16 10:59 UTC, phani-perla1 commented on test/end-to-end/mvFeatures/redact.js
> +}).tag('@ci')
I had a call with Michael and the new feature tests will run both AAT as well as on Preview

2023-01-16 10:59 UTC, phani-perla1 commented on test/end-to-end/mvFeatures/redact.js
> +}).tag('@ci')
I had a call with Michael and the new feature tests will run both AAT as well as on Preview

2023-01-16 11:00 UTC, phani-perla1 commented on test/end-to-end/helpers/mvCaseHelper.js
> +  await executeTestsOnPreview(I, caseId, mediaType);
I had a call with Michael and the new feature tests will run both AAT as well as on Preview

2023-02-02 16:57 UTC, MunishSharmaHMCTS approved these changes

2023-02-02 16:59 UTC, merged